apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-persistent
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-persistent
    spec:
      containers:
        - name: redis
          image: redis:5-alpine
          args: ["--appendonly", "yes"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      name: redis
  selector:
    app: redis-persistent
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: redis
spec:
  #storageClassName: "supercheap"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
