{{- if .Values.cowconfig.http.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "krazy-cow.fullname" . }}-creds
  labels:
    {{- include "krazy-cow.labels" . | nindent 4 }}
type: Opaque
stringData:
  credentials.txt: |-
{{- include "krazy-cow.getCredentialsString" . | nindent 4 }}
{{- end }}
