apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "krazy-cow.fullname" . }}
  labels:
    {{- include "krazy-cow.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "krazy-cow.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "krazy-cow.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "krazy-cow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if .Values.cowconfig.http.tls.enabled }}
            - name: https
              containerPort: 8443
              protocol: TCP
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config/
            {{- if .Values.cowconfig.http.auth.enabled }}
            - name: cow-creds
              mountPath: /creds/
            {{- end }}


      volumes:
        - name: config
          configMap:
            name: {{ template "krazy-cow.fullname" . }}-config
      {{- if .Values.cowconfig.http.auth.enabled }}
        - name: cow-creds
          secret:
            secretName: {{ include "krazy-cow.fullname" . }}-creds
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
