{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "krazy-cow.serviceAccountName" . }}
  labels:
{{ include "krazy-cow.labels" . | nindent 4 }}
{{- end -}}
