# image: docker:git
image: cloudowski/gitlab-runner:0.1

services:
  - docker:dind

# variables:
#   DOCKER_DRIVER: overlay2
#   CONTAINER_IMAGE: registry.gitlab.com/codebabel/$CI_PROJECT_NAME #Workaround https://gitlab.com/gitlab-org/gitlab-ce/issues/23339

stages:
  - test
  - build and publish

test:
  stage: test
  image: golang:1.11
  # image: cloudowski/gitlab-runner:0.1
  script:
    - mkdir -p /go/src/gitlab.com/$CI_PROJECT_NAMESPACE
    - cp -r /builds/$CI_PROJECT_NAMESPACE /go/src/gitlab.com/
    - cd /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/krazy-cow
    - go get -d
    # - go test ./... -v
    - make test

build-and-publish:
  stage: build and publish
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
  script:
    - make buildimg
    - make push
    # - docker build -t cloudowski/krazy-cow .
    # - docker push cloudowski/krazy-cow
