cow:
    say: "Moooooo, I'm a cow"
    initmood: 20
    moodchanger:
        enabled: false
        interval: 5
        change: -1
    pasture:
        path: /pasture
        interval: 5
logging:
    requests: true
