# build stage
FROM golang:alpine AS build-env
RUN apk add --no-cache git
WORKDIR $GOPATH/src/gitlab.com/cloudowski/krazy-cow
COPY . .
COPY config /app/config/

RUN go get -v -d
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo -ldflags="-w -s" -o /app/goapp

FROM scratch
WORKDIR /app
COPY --from=build-env /app/* .
EXPOSE 8080
USER 1001
ENTRYPOINT [ "/app/goapp" ]
