orbs:
  docker: circleci/docker@0.5.20

version: 2.1
jobs:
  build-app:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cloudowski/krazy-cow
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: |
          export VERSION=latest
          export TAG=${CIRCLE_SHA1:0:7}
          [ -n "$CIRCLE_TAG" ] && VERSION="$TAG" 
          mkdir app
          go build -ldflags="-w -s -X main.version=$VERSION -X main.gitCommit=$TAG" -o app/krazycow
          cp -a config web app/
          echo "Version built: $VERSION ($TAG)"
      - persist_to_workspace:
          root: .
          paths:
            - app/

workflows:
  version: 2
  build-krazycow:
    jobs:
      - build-app:
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              only: /.*/
      # publish "dev" version
      - docker/publish:
          dockerfile: Dockerfile.ci
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: dev
          before_build:
            - attach_workspace:
                at: app
          requires:
            - build-app
          filters:
            branches:
              ignore: master
      # publish tagged version
      - docker/publish:
          dockerfile: Dockerfile.ci
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: "$CIRCLE_TAG,latest"
          before_build:
            - attach_workspace:
                at: app
          requires:
            - build-app
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
