version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cloudowski/krazy-cow
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: |
          export VERSION=latest
          export TAG=${CIRCLE_TAG:0:7}
          [ -n "$CIRCLE_TAG" ] && VERSION="$TAG" 
          go build -ldflags="-w -s -X main.version=$VERSION -X main.gitCommit=$TAG" -o krazycow
          echo "Version built: $VERSION ($TAG)"
      - store_artifacts:
          path: krazycow
          destination: krazycow
# workflows:
#   version: 2
#   build-master:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
