version: 2
jobs:
  build-app:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cloudowski/krazy-cow
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: |
          export VERSION=latest
          export TAG=${CIRCLE_TAG:0:7}
          [ -n "$CIRCLE_TAG" ] && VERSION="$TAG" 
          mkdir app
          go build -ldflags="-w -s -X main.version=$VERSION -X main.gitCommit=$TAG" -o app/krazycow
          cp -a config web app/
          echo "Version built: $VERSION ($TAG)"
      - persist_to_workspace:
          root: .
          paths:
            - app/
      # - store_artifacts:
      #     path: krazycow
      #     destination: krazycow
  build-and-publish:
    environment:
      IMAGE_NAME: cloudowski/krazy-cow
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: app
      - run:
          name: Build Docker image
          command: |
            # cp -a /tmp/workspace/app .
            docker build -t $IMAGE_NAME:dev -f Dockerfile.ci .

workflows:
  version: 2
  build-master:
    jobs:
      - build-app
      - build-and-publish:
          requires:
            - build-app
#           filters:
#             branches:
#               only: master
