orbs:
  docker: circleci/docker@0.5.20

version: 2.1

jobs:
  build-app:
    docker:
      - image: circleci/golang:1.13

    working_directory: /go/src/github.com/cloudowski/krazy-cow
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
      - run: |
          export VERSION=latest
          [ -n "$CIRCLE_TAG" ] && VERSION="$CIRCLE_TAG" 
          export COMMIT=${CIRCLE_SHA1:0:7}
          mkdir app
          go build -ldflags="-w -s -X main.version=$VERSION -X main.gitCommit=$COMMIT" -o app/krazycow
          cp -a config web app/
          echo "Version built: $VERSION ($COMMIT)"
      - persist_to_workspace:
          root: .
          paths:
            - app/
  smoketest:
    docker:
      - image: curlimages/curl
    steps:
      - run: |
          docker run -d -p 8080:8080 $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1
          curl $@ -m 3 -s -w "%{http_code}" localhost:8080

workflows:
  version: 2
  build-krazycow:
    jobs:
      - build-app:
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              only: /.*/
      # perform tests
      - docker/build:
          dockerfile: Dockerfile.ci
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          before_build:
            - attach_workspace:
                at: app
          requires:
            - build-app
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              only: /.*/
      - smoketest:
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              only: /.*/
      # publish "dev" version
      - docker/publish:
          dockerfile: Dockerfile.ci
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: dev
          before_build:
            - attach_workspace:
                at: app
          requires:
            - build-app
          filters:
            branches:
              ignore: master
      # publish tagged version
      - docker/publish:
          dockerfile: Dockerfile.ci
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: "$CIRCLE_TAG,latest"
          before_build:
            - attach_workspace:
                at: app
          requires:
            - build-app
          filters:
            tags:
              only: /^[0-9]+.*/
            branches:
              ignore: /.*/
