apiVersion: apps/v1
kind: Deployment
metadata:
  name: cow

  labels:
    app: cow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cow
  template:
    metadata:
      labels:
        app: cow
    spec:
      # terminationGracePeriodSeconds: 5

      containers:
        - image: cloudowski/krazy-cow:latest
          imagePullPolicy: Always
          name: cow

          livenessProbe:
            httpGet:
              path: /healthz
              # path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            failureThreshold: 2

          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: cow-config
              mountPath: /config/
            - name: pasture
              mountPath: /pasture

      initContainers:
        - name: pasture
          image: busybox
          command:
            ["sh", "-c", "for i in `seq 1 20`;do touch /pasture/tuft$i;done"]
          volumeMounts:
            - name: pasture
              mountPath: /pasture

      volumes:
        - name: cow-config
          configMap:
            name: cow-config
        - name: pasture
