apiVersion: v1
kind: ConfigMap
metadata:
  name: cow-config
data:
  cowconfig.yaml: |
    cow:
      say: "Moooooo, I'm a cow CONTAINER"
      initmood: 22
      moodchanger:
        enabled: true
        interval: 2
        change: -1
      pasture:
        path: /pasture
        interval: 3
    logging:
      requests: true
