apiVersion: apps/v1
kind: Deployment
metadata:
  name: cow

  labels:
    app: cow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: cow
  template:
    metadata:
      labels:
        app: cow
    spec:
      # terminationGracePeriodSeconds: 5

      containers:
        - image: cloudowski/trapped-cow:latest
          name: cow

          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 5
          #   periodSeconds: 5

          ports:
            - containerPort: 8080
              name: http
      #   envFrom:
      #   - configMapRef:
      #       name: cow-config
      #   volumeMounts:
      #   - name: cow-secret
      #     mountPath: /run/secrets/cow
      # volumes:
      # - name: cow-secret
      #   secret:
      #     secretName: pets-admin-password
