cow:
    say: "Moooooo, I'm a cow"
    initmood: 20
    moodchanger:
        enabled: false
        interval: 5
        change: -1
    shepherd:
        redisurl: redis:6379
    pasture:
        path: /pasture
        interval: 5
http:
    port: 8080
    tls:
        port: 8443
        enabled: false
        cert: config/server.crt
        key: config/server.key
    auth:
        enabled: false
        credentials: config/credentials.txt

logging:
    requests: true
    level: DEBUG # see https://godoc.org/github.com/op/go-logging#Level
    # level: NOTICE # see https://godoc.org/github.com/op/go-logging#Level
    # level: INFO # see https://godoc.org/github.com/op/go-logging#Level
