cow:
    say: "Moooooo, I'm a cow"
    initmood: 20
    moodchanger:
        enabled: false
        interval: 5
        change: -1
    pasture:
        path: /pasture
        interval: 5
http:
    port: 8080
    tls:
        port: 8443
        enabled: false
        cert: config/server.crt
        key: config/server.key
    auth:
        enabled: false
        credentials: config/credentials.txt

logging:
    requests: true
