resources:
- ../base
- namespace.yaml

images:
- name: cloudowski/krazy-cow
  newName: sdasdsd/asdadad
  newTag: xxx
- name: cow
  newName: asdadad
  newTag: xxx
- name: krazy-cow
  newName: asdadad
  newTag: xxx

namespace: kcow-stage
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
