apiVersion: apps/v1
kind: Deployment
metadata:
  name: cow
spec:
  template:
    spec:
      containers:
        - image: harbor.192.168.99.147.nip.io/library/krazy-cow:latest
          imagePullPolicy: Always
          name: cow
